import { Router } from "express";
import { measure } from "./measure";
import { distance } from "./distance";
import { buffer } from "./buffer";
import { overlay } from "./overlay";
import { relates } from "./relates";
import { hull } from "./hull";
import { simplify } from "./simplify";
import { interpolate } from "./interpolate";
import { reference } from "./reference";
import { meta } from "./meta";
export const api = Router();
api.get("/health", (_req, res) => { res.json({ data: { status: "ok", service: "Tessera" } }); });
api.use("/measure", measure);
api.use("/distance", distance);
api.use("/buffer", buffer);
api.use("/overlay", overlay);
api.use("/relates", relates);
api.use("/hull", hull);
api.use("/simplify", simplify);
api.use("/interpolate", interpolate);
api.use("/reference", reference);
api.use("/meta", meta);
